name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        cache-suffix: python-${{ matrix.python-version }}

    - name: Set up Python and install dependencies
      run: |
        uv python install ${{ matrix.python-version }}
        uv sync --frozen --all-groups
        uv pip install -e .

    - name: Run Ruff linter
      run: |
        PYTHONPATH=. uv run ruff check . --output-format=github

    - name: Run Ruff formatter check
      run: |
        PYTHONPATH=. uv run ruff format --check .

    - name: Run MyPy type checker
      run: |
        PYTHONPATH=. uv run mypy

    - name: Run security checks (Bandit)
      run: |
        PYTHONPATH=. uv run bandit -r sqlllm/ -f json -o bandit-report.json || true
        PYTHONPATH=. uv run bandit -r sqlllm/ || true

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        cache-suffix: python-${{ matrix.python-version }}

    - name: Set up Python and install dependencies
      run: |
        uv python install ${{ matrix.python-version }}
        uv sync --frozen --all-groups
        uv pip install -e .

    - name: Run pytest
      run: |
        PYTHONPATH=. uv run pytest -v --cov=sqlllm --cov-report=term-missing
